### ISSUE TITLE
Ability to pass in token

### ISSUE THREAD

**Issue by jwhitcraft** [morozov/diff-sniffer-pull-request#2]
I'd like to use with with Jenkins, but to do so, i'd need to pass in an readly set token.

Is there a way to do this?

Thanks.

**Comment by morozov** [comment]
You can manually create configuration file containing the token:
```
↪  cat $HOME/.diff-sniffer/config.php 
<?php

return array (
  'token' => 'TOKEN-IS-SAVED-HERE',
);
```
